import React from "react";
import { Emoji } from "emoji-mart";

export const OfficialMoviesGenres = [
  { id: 28, name: "Action" },
  { id: 12, name: "Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 14, name: "Fantasy" },
  { id: 36, name: "History" },
  { id: 27, name: "Horror" },
  { id: 10402, name: "Music" },
  { id: 9648, name: "Mystery" },
  { id: 10749, name: "Romance" },
  { id: 878, name: "Science Fiction" },
  { id: 10770, name: "TV Movie" },
  { id: 53, name: "Thriller" },
  { id: 10752, name: "War" },
  { id: 37, name: "Western" },
];
const rates = ["Excellent", "Good", "OK", "Bad"];

export const Reviews = [
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
];

export const OfficialSeriesGenres = [
  {
    id: 10759,
    name: "Action & Adventure",
  },
  {
    id: 16,
    name: "Animation",
  },
  {
    id: 35,
    name: "Comedy",
  },
  {
    id: 80,
    name: "Crime",
  },
  {
    id: 99,
    name: "Documentary",
  },
  {
    id: 18,
    name: "Drama",
  },
  {
    id: 10751,
    name: "Family",
  },
  {
    id: 10762,
    name: "Kids",
  },
  {
    id: 9648,
    name: "Mystery",
  },
  {
    id: 10763,
    name: "News",
  },
  {
    id: 10764,
    name: "Reality",
  },
  {
    id: 10765,
    name: "Sci-Fi & Fantasy",
  },
  {
    id: 10766,
    name: "Soap",
  },
  {
    id: 10767,
    name: "Talk",
  },
  {
    id: 10768,
    name: "War & Politics",
  },
  {
    id: 37,
    name: "Western",
  },
];

export const Credits = {
  id: 718867,
  cast: [
    {
      cast_id: 1,
      character: "",
      credit_id: "5ef4a174c3bffe00356bf976",
      gender: 2,
      id: 1485137,
      name: "Hong Beom-gi",
      order: 1,
      profile_path: null,
    },
    {
      cast_id: 3,
      character: "",
      credit_id: "5f1b0899176a9400390769cd",
      gender: 0,
      id: 2595112,
      name: "Kang Shin-hyung",
      order: 2,
      profile_path: null,
    },
  ],
  crew: [
    {
      credit_id: "5ef4a193459ad60034dfb2ce",
      department: "Directing",
      gender: 0,
      id: 2691195,
      job: "Director",
      name: "Ahn Byoung-wook",
      profile_path: null,
    },
  ],
};

export const Movie = {
  adult: false,
  backdrop_path: "/53aUwtolUZxgzMr2KbDpOnD8jo3.jpg",
  belongs_to_collection: null,
  budget: 0,
  genres: [
    { id: 16, name: "Animation" },
    { id: 10751, name: "Family" },
  ],
  homepage: "https://www.netflix.com/title/80991326",
  id: 718867,
  id: String,
  imdb_id: String,
  original_language: "en",
  original_title: "The Larva Island Movie",
  overview:
    "Back at home, Chuck relates the island shenanigans of his larva pals Red and Yellow to a skeptical reporter in this movie sequel to the hit cartoon.",
  popularity: 80.193,
  poster_path: "/uHdxICUIRGoJjK67aOp3ykvL8ZW.jpg",
  production_companies: [
    {
      id: 137625,
      logo_path: null,
      name: "TUBA Enter py-3tainment",
      origin_country: "",
    },
  ],
  production_countries: [{ iso_3166_1: "KR", name: "South Korea" }],
  release_date: "2020-07-23",
  revenue: 0,
  runtime: 89,
  spoken_languages: [{ iso_639_1: "ko", name: "한국어/조선말" }],
  status: "Released",
  tagline: "",
  title: "The Larva Island Movie",
  video: false,
  vote_average: 8,
  vote_count: 2,
};

export const FirstMovieTrailers = {
  id: 583083,
  results: [
    {
      id: "5c6b0b76c3a3683bf0dab609",
      iso_639_1: "en",
      iso_3166_1: "US",
      key: "_Br5Sm6sf24",
      name: "The Kissing Booth 2 | Official Announcement [HD] | Netflix",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
    },
    {
      id: "5f0356f38a0e9b003499389f",
      iso_639_1: "en",
      iso_3166_1: "US",
      key: "fjVonI2oVeM",
      name: "The Kissing Booth 2 | Official Trailer | Netflix",
      site: "YouTube",
      size: 1080,
      type: "Trailer",
    },
  ],
};

export const Announcements = [
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Information",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
];

export const Comments = [
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    date: Date.now(),
    review_id: 1,
    deleted: false,
    movie_title: "Venom",
    reported: false,
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
];

export const TrendingMovies = {
  page: 1,
  results: [
    {
      id: 583083,
      video: false,
      vote_count: 3,
      vote_average: 8.7,
      title: "The Kissing Booth 2",
      release_date: "2020-07-24",
      original_language: "en",
      original_title: "The Kissing Booth 2",
      genre_ids: [35, 10749],
      backdrop_path: "/wO5QSWZPBT71gMLvrRex0bVc0V9.jpg",
      adult: false,
      overview:
        "High school senior Elle juggles a long-distance relationship with her dreamy boyfriend Noah, college applications, and a new friendship with a handsome classmate that could change everything.",
      poster_path: "/pwmtGo0mTjTqWZwk3k3VSWtygxj.jpg",
      popularity: 57.144,
      media_type: "movie",
    },
    {
      id: 516486,
      video: false,
      vote_count: 512,
      vote_average: 7.6,
      title: "Greyhound",
      release_date: "2020-07-10",
      original_language: "en",
      original_title: "Greyhound",
      genre_ids: [28, 18, 10752],
      backdrop_path: "/xXBnM6uSTk6qqCf0SRZKXcga9Ba.jpg",
      adult: false,
      overview:
        "A first-time captain leads a convoy of allied ships carrying thousands of soldiers across the treacherous waters of the “Black Pit” to the front lines of WW2. With no air cover protection for 5 days, the captain and his convoy must battle the surrounding enemy Nazi U-boats in order to give the allies a chance to win the war.",
      poster_path: "/kjMbDciooTbJPofVXgAoFjfX8Of.jpg",
      popularity: 263.335,
      media_type: "movie",
    },
    {
      id: 718867,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "The Larva Island Movie",
      release_date: "2020-07-23",
      original_language: "en",
      original_title: "The Larva Island Movie",
      genre_ids: [16, 10751],
      backdrop_path: "/53aUwtolUZxgzMr2KbDpOnD8jo3.jpg",
      adult: false,
      overview:
        "Back at home, Chuck relates the island shenanigans of his larva pals Red and Yellow to a skeptical reporter in this movie sequel to the hit cartoon.",
      poster_path: "/uHdxICUIRGoJjK67aOp3ykvL8ZW.jpg",
      popularity: 57.281,
      media_type: "movie",
    },
    {
      id: 547016,
      video: false,
      vote_count: 1203,
      vote_average: 7.4,
      title: "The Old Guard",
      release_date: "2020-07-10",
      original_language: "en",
      original_title: "The Old Guard",
      genre_ids: [28, 14],
      backdrop_path: "/m0ObOaJBerZ3Unc74l471ar8Iiy.jpg",
      adult: false,
      overview:
        "Four undying warriors who've secretly protected humanity for centuries become targeted for their mysterious powers just as they discover a new immortal.",
      poster_path: "/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg",
      popularity: 234.258,
      media_type: "movie",
    },
    {
      id: 385103,
      video: false,
      vote_count: 203,
      vote_average: 7.8,
      title: "Scoob!",
      release_date: "2020-07-08",
      original_language: "en",
      original_title: "Scoob!",
      genre_ids: [12, 16, 35, 9648, 10751],
      backdrop_path: "/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg",
      adult: false,
      overview:
        "In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.",
      poster_path: "/jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg",
      popularity: 126.33,
      media_type: "movie",
    },
    {
      adult: false,
      backdrop_path: "/61uvGsh4HmhEBDGIUuSEpIjYHdF.jpg",
      genre_ids: [80, 53],
      id: 673174,
      original_language: "es",
      original_title: "Ofrenda a la tormenta",
      overview:
        "Inspector Amaia Salazar confronts the origins of her nightmares as she unfolds the darkest secrets of the Baztan valley. Part 3 in the Baztan Trilogy.",
      poster_path: "/rZChaVFyGnWeKUWzDaNgF7xmT2C.jpg",
      release_date: "2020-07-24",
      title: "Offering to the Storm",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 44.383,
      media_type: "movie",
    },
    {
      id: 587496,
      video: false,
      vote_count: 1,
      vote_average: 7,
      title: "The Rental",
      release_date: "2020-07-23",
      original_language: "en",
      original_title: "The Rental",
      genre_ids: [27, 53],
      backdrop_path: "/2gBMBfmQvHeOQQ5PiKiuxVdGs77.jpg",
      adult: false,
      overview:
        "Two couples rent a vacation home for what should be a celebratory weekend get-away.",
      poster_path: "/cgRTJ8d5MlwSwSsv4WwPTh4Atan.jpg",
      popularity: 59.008,
      media_type: "movie",
    },
    {
      adult: false,
      backdrop_path: "/4NQFjYust0K9WdGnXF1a4FDiDap.jpg",
      genre_ids: [80, 53],
      id: 526973,
      original_language: "en",
      original_title: "Target Number One",
      overview:
        "Ex heroin junkie, Daniel Léger, gets involved in a drug deal with the wrong people for the wrong reasons. When the deal goes sour, Daniel gets thrown into a Thai prison and slapped with a 100-year sentence. While he tries to survive his Bangkok incarceration, the news of his conviction captures the attention of Globe and Mail journalist Victor Malarek, who decides to go after the shady undercover cops responsible for wrongly accusing Daniel.",
      poster_path: "/npOZUVjSUJbL3WkL9jZBZ6gwURk.jpg",
      release_date: "2020-07-10",
      title: "Target Number One",
      video: false,
      vote_average: 2,
      vote_count: 1,
      popularity: 5.789,
      media_type: "movie",
    },
    {
      id: 299534,
      video: false,
      vote_count: 14277,
      vote_average: 8.3,
      title: "Avengers: Endgame",
      release_date: "2019-04-24",
      original_language: "en",
      original_title: "Avengers: Endgame",
      genre_ids: [28, 12, 878],
      backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
      adult: false,
      overview:
        "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
      poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      popularity: 61.952,
      media_type: "movie",
    },
    {
      id: 430155,
      video: false,
      vote_count: 102,
      vote_average: 5.9,
      title: "Coma",
      release_date: "2019-11-19",
      original_language: "ru",
      original_title: "Koma",
      genre_ids: [28, 14, 878],
      backdrop_path: "/6kJKTKnnPbpyeqCgodqgjkI9aMk.jpg",
      adult: false,
      overview:
        "A young and talented architect comes to his senses after a horrific accident only to find himself in the odd dystopian world. A world that is filled with the memories of all current coma patients. Just like a human memory this world is fragmental, chaotic and unstable. This is COMA: icecaps, rivers and cities can all exist in a space of a single room and laws of physics are no longer laws as they can be bent.",
      poster_path: "/1hVEsBS4vnozB1yAsMiqW0IMxyp.jpg",
      popularity: 105.203,
      media_type: "movie",
    },
    {
      id: 645484,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "Dil Bechara",
      release_date: "2020-07-24",
      original_language: "hi",
      original_title: "Dil Bechara",
      genre_ids: [18, 10749],
      backdrop_path: "/2DU9RElgCrjbzJM1Hjgotojj2jI.jpg",
      adult: false,
      overview:
        "Dil Bechara (transl. The helpless heart) is an Indian Hindi-language coming of age romantic comedy film. It is based on author John Green's 2012 novel The Fault in Our Stars, which was also adapted in film as The Fault in Our Stars (2014).",
      poster_path: "/lJri7i2XPdzKwfFLQ4cEDJJ6eNq.jpg",
      popularity: 29.077,
      media_type: "movie",
    },
    {
      id: 454983,
      video: false,
      vote_count: 4731,
      vote_average: 7.3,
      title: "The Kissing Booth",
      release_date: "2018-05-11",
      original_language: "en",
      original_title: "The Kissing Booth",
      genre_ids: [35, 10749],
      backdrop_path: "/fHEu7n8WJKkVuUPEen6Ndyz642g.jpg",
      adult: false,
      overview:
        "When teenager Elle's first kiss leads to a forbidden romance with the hottest boy in high school, she risks her relationship with her best friend.",
      poster_path: "/7Dktk2ST6aL8h9Oe5rpk903VLhx.jpg",
      popularity: 41.377,
      media_type: "movie",
    },
    {
      id: 714521,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "The Big Ugly",
      release_date: "2020-07-31",
      original_language: "en",
      original_title: "The Big Ugly",
      genre_ids: [18],
      backdrop_path: "/cOvRVxGytvrGwZ74T4RqBpbdtBd.jpg",
      adult: false,
      overview:
        "Neeyln has always been the loyal enforcer for crime boss Harris back in London, taking care of problems and people that disrupt his illicit business. When Harris strikes a deal with an old friend -- American oilman Preston -- they find themselves in the wild hills of West Virginia. Contracts are signed and the whiskey flows in celebration, but overnight Neelyn's girlfriend disappears, last seen with Preston's wayward son Junior. Lines are Drawn between family and friends, but nothing will stop Neelyn from getting answers -- and retribution.",
      poster_path: "/34TU17zW5ggpYxk20drTN6srmqy.jpg",
      popularity: 40.956,
      media_type: "movie",
    },
    {
      id: 653615,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "Amulet",
      release_date: "2020-08-06",
      original_language: "en",
      original_title: "Amulet",
      genre_ids: [27],
      backdrop_path: "/pEAppdnhsLgu44Cv0i7hYlf8USE.jpg",
      adult: false,
      overview:
        "Tomaz, an ex-soldier now homeless in London, is offered a place to stay at a decaying house, inhabited by a young woman and her dying mother. As he starts to fall for Magda, Tomaz cannot ignore his suspicion that something insidious might also be living alongside them.",
      poster_path: "/af8CM0ETQOZcGqXOhx4Dpq1UOA8.jpg",
      popularity: 10.902,
      media_type: "movie",
    },
    {
      adult: false,
      backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
      genre_ids: [80, 53, 18],
      id: 475557,
      original_language: "en",
      original_title: "Joker",
      overview:
        "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
      poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
      release_date: "2019-10-02",
      title: "Joker",
      video: false,
      vote_average: 8.2,
      vote_count: 13893,
      popularity: 112.986,
      media_type: "movie",
    },
    {
      id: 723895,
      video: false,
      vote_count: 0,
      vote_average: 0,
      title: "Dragons: Rescue Riders: Secrets of the Songwing",
      release_date: "2020-07-24",
      original_language: "en",
      original_title: "Dragons: Rescue Riders: Secrets of the Songwing",
      genre_ids: [16, 10751],
      backdrop_path: "/yKaKpY82MhGfwaiWquTfgaBWpns.jpg",
      adult: false,
      overview:
        "When a musical Dragon with a beautiful voice hypnotizes the Dragons and people of Huttsgalor, the Rescue Riders have to find a way to break the spell.",
      poster_path: "/7ECPZaRczTQiUgPtZzyOiHxlfbe.jpg",
      popularity: 26.578,
      media_type: "movie",
    },
    {
      id: 581392,
      video: false,
      vote_count: 13,
      vote_average: 6.3,
      title: "Peninsula",
      release_date: "2020-07-15",
      original_language: "ko",
      original_title: "반도",
      genre_ids: [28, 27, 53],
      backdrop_path: "/oamFZb8Gj5NJ24OLDd07wyNVX4N.jpg",
      adult: false,
      overview:
        "Peninsula takes place four years after Train to Busan as the characters fight to escape the land that is in ruins due to an unprecedented disaster.",
      poster_path: "/7S9RvfMBWSTlUZ4VbxDY7oLeenk.jpg",
      popularity: 72.859,
      media_type: "movie",
    },
    {
      id: 603119,
      video: false,
      vote_count: 9,
      vote_average: 6.6,
      title: "The Silencing",
      release_date: "2020-07-18",
      original_language: "en",
      original_title: "The Silencing",
      genre_ids: [28, 80, 53],
      backdrop_path: "/wmue8ULgckHrTc9eXALYoDbOAq0.jpg",
      adult: false,
      overview:
        "A reformed hunter becomes involved in a deadly game of cat and mouse when he and the local sheriff set out to track a vicious killer who may have kidnapped his daughter years ago.",
      poster_path: "/osoQHmiOMlk1v4sNyIMkO8RF4cJ.jpg",
      popularity: 55.262,
      media_type: "movie",
    },
    {
      id: 714375,
      video: false,
      vote_count: 74,
      vote_average: 5.1,
      title: "Fatal Affair",
      release_date: "2020-07-16",
      original_language: "en",
      original_title: "Fatal Affair",
      genre_ids: [53],
      backdrop_path: "/lMbUiOZh8wELqY63v3ou54yTvEG.jpg",
      adult: false,
      overview:
        "Ellie tries to mend her marriage with her husband Marcus after a brief encounter with an old friend, David, only to find that David is more dangerous and unstable than she'd realized.",
      poster_path: "/f4EAJ6PXNbxBb2xrdTrT2SlJlCH.jpg",
      popularity: 81.634,
      media_type: "movie",
    },
    {
      id: 181812,
      video: false,
      vote_count: 5291,
      vote_average: 6.6,
      title: "Star Wars: The Rise of Skywalker",
      release_date: "2019-12-18",
      original_language: "en",
      original_title: "Star Wars: The Rise of Skywalker",
      genre_ids: [28, 12, 878],
      backdrop_path: "/SPkEiZGxq5aHWQ2Zw7AITwSEo2.jpg",
      adult: false,
      overview:
        "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
      poster_path: "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
      popularity: 63.336,
      media_type: "movie",
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};

export const Promotions = [
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },

  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },

  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },

  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    rating: "Excellent",
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 1,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    rating: "Excellent",
    author: 2,
    date: Date.now(),
    status: "Sent",
    start_date: Date.now(),
    end_date: Date.now(),
    title: "Promotion",
    movie_title: "Venom",
    type: "review",
    review_id: 5,
    active_status: "Active",
    _id: 5,
    review:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },

  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Paused",
    status: "Drafted",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Finished",
    status: "Drafted",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    type: "comment",
    active_status: "Active",
    status: "Sent",
    date: Date.now(),
    comment_id: 1,
    deleted: false,
    title: "Promotion",
    movie_title: "Venom",
    _id: 5,
    comment:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
];

export const PublicUsers = {
  1: {
    email: "sabrina@gmail.com",
    role: "admin",
    photo:
      "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    display_name: "Sabrina",
  },
  2: {
    email: "paula@gmail.com",
    role: "user",
    photo:
      "https://images.pexels.com/photos/3779853/pexels-photo-3779853.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    display_name: "Paula",
  },
  3: {
    email: "paula@gmail.com",
    role: "user",
    photo:
      "https://images.pexels.com/photos/3779853/pexels-photo-3779853.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    display_name: "Andrew",
  },
  4: {
    email: "paula@gmail.com",
    role: "user",
    photo:
      "https://images.pexels.com/photos/3779853/pexels-photo-3779853.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    display_name: "John",
  },
};

export const Ratings = [
  {
    name: "Excellent",
    element: (
      <div className="text-center py-3" style={{ lineHeight: "100%" }}>
        <Emoji emoji="fire" set="facebook" size={24} />
      </div>
    ),
  },
  {
    name: "Good",
    element: (
      <div className="text-center py-3" style={{ lineHeight: "100%" }}>
        <Emoji emoji="heart" set="facebook" size={24} />
      </div>
    ),
  },
  {
    name: "OK",
    element: (
      <div className="text-center py-3" style={{ lineHeight: "100%" }}>
        <Emoji emoji="heavy_division_sign" set="facebook" size={24} />
      </div>
    ),
  },
  {
    name: "Bad",
    element: (
      <div className="text-center py-3" style={{ lineHeight: "100%" }}>
        <Emoji emoji="shit" set="facebook" size={24} />
      </div>
    ),
  },
];

export const Notifications = [
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "App",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "App",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 2,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "App",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "App",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
  {
    author: 1,
    title: "Notification title",
    start_date: Date.now(),
    end_date: Date.now(),
    type: "Email",
    status: "Drafted",
    _id: 5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat neque in diam egestas, vel vehicula erat blandit. Nulla aliquam varius justo quis pretium. Praesent urna metus, eleifend non porta vel, blandit vitae orci. Sed blandit at dolor in imperdiet. Fusce nec nisl odio. Nullam et eros mollis enim cursus ornare ac quis purus. Aenean id sem varius, pretium sem ut, eleifend orci.",
  },
];
